services:
  - type: web
    name: nyc-subway-tracker
    env: python
    buildCommand: "pip install -r requirements.txt && python generate_stations.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

